PersonalWebsite.AdminWeb/Controllers/KeyValueController.cs
using Microsoft.AspNetCore.Mvc;
using PersonalWebsite.AdminWeb.Models;
using PersonalWebsite.IService;

namespace PersonalWebsite.AdminWeb.Controllers
{
    public class KeyValueController : Controller
    {
        IKeyValueService KeyValueService { get; set; }
        public KeyValueController(IKeyValueService KeyValueService)
        {
            this.KeyValueService = KeyValueService;
        }

        [HttpGet]
        public IActionResult List()
        {
            return View();
        }
        [HttpPost]
        public IActionResult List(string str, int page, int limit)
        {
            var keyValues = KeyValueService.GetAll(limit, (page - 1) * limit);
            Result result = new Result();
            result.Code = 0;
            result.Data = keyValues;
            result.Count = (int)KeyValueService.Count();
            return Json(result);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(KeyValueAddModel model)
        {
            if (!ModelState.IsValid)
            {
                return Json(new FormResult() { status = 1, msg = "数据验证未通过" });
            }
            KeyValueService.AddNew(model.Key, model.Value);
            return Json(new FormResult() { status = 0, msg = "保存成功" });
        }
        [HttpGet]
        public IActionResult Edit(long id)
        {
            var keyValue = KeyValueService.GetById(id);
            KeyValueEditModel model = new KeyValueEditModel
            {
                Id = keyValue.Id,
                Key = keyValue.Key,
                Value = keyValue.Value
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult Edit(KeyValueEditModel model)
        {
            FormResult result = new FormResult();
            try
            {
                KeyValueService.Edit(model.Id, model.Key, model.Value);
                result.msg = "保存成功";
            }
            catch
            {
                result.msg = "保存失败";
            }
            return Json(result);
        }
    }
}

PersonalWebsite.AdminWeb/Views/KeyValue/Add.cshtml
@model KeyValueAddModel
@{
    ViewData["Title"] = "添加字典";
}
@section toolbar{
    <h3>添加字典</h3>
}
<form id="form1" class="layui-form" asp-action="Add" asp-controller="KeyValue" method="post">
    <div class="layui-form-item">
        <label class="layui-form-label">关键字</label>
        <div class="layui-input-block">
            <input type="text" asp-for="Key" lay-verify="required" autocomplete="off" placeholder="请输入关键字" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">值</label>
        <div class="layui-input-block">
            <input type="text" asp-for="Value" lay-verify="required" autocomplete="off" placeholder="请输入值" class="layui-input">
        </div>
    </div>

    <div class="layui-form-item">
        <div class="layui-input-block">
            <button class="layui-btn" lay-filter="*" alert lay-submit>保存</button>
        </div>
    </div>
</form>

PersonalWebsite.AdminWeb/Views/KeyValue/Edit.cshtml
@model KeyValueEditModel
@{
    ViewData["Title"] = "编辑字典";
}
@section toolbar{
    <h3>编辑字典</h3>
}
<form id="form1" class="layui-form" asp-action="Edit" asp-controller="KeyValue" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="layui-form-item">
        <label class="layui-form-label">关键字</label>
        <div class="layui-input-block">
            <input type="text" asp-for="Key" lay-verify="required" autocomplete="off" placeholder="请输入关键字" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">值</label>
        <div class="layui-input-block">
            <input type="text" asp-for="Value" lay-verify="required" autocomplete="off" placeholder="请输入值" class="layui-input">
        </div>
    </div>

    <div class="layui-form-item">
        <div class="layui-input-block">
            <button class="layui-btn" lay-filter="*" alert lay-submit>保存</button>
        </div>
    </div>
</form>

PersonalWebsite.AdminWeb/Views/KeyValue/List.cshtml
@{
    ViewData["Title"] = "字典管理";
}

@section toolbar{
    <div class="layui-form-item">
        <div class="layui-inline">
            <label class="layui-form-label">关键字</label>
            <div class="layui-input-block">
                <input type="text" name="poster" placeholder="请输入" autocomplete="off" class="layui-input">
            </div>
        </div>
        <div class="layui-inline">
            <button class="layui-btn layuiadmin-btn-forum-list" lay-submit="" lay-filter="LAY-app-forumlist-search">
                <i class="layui-icon layui-icon-search layuiadmin-button-btn"></i>
            </button>
        </div>
    </div>
}
<script type="text/html" id="toolbarDemo">
    <div class="layui-btn-container">
        <button class="layui-btn layui-btn-sm" lay-event="add">添加字典</button>
    </div>
</script>
<table class="layui-hide" id="myTable" lay-filter="myTable" lay-even=""></table>
<script type="text/html" id="barDemo">
    <a class="layui-btn layui-btn-primary layui-btn-xs" lay-event="edit">编辑</a>
    <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
</script>
@section scripts{

    <script>
        layui.use(['table','layer'], function () {
            var table = layui.table
                , layer = layui.layer;
            //第一个实例
            table.render({
                elem: '#myTable'
                , url: '@Url.Content("~/KeyValue/List")' //数据接口
                , method: 'post'
                , page: true //开启分页
                , limit: 10
                , cellMinWidth: 150
                , toolbar: '#toolbarDemo'
                , title: '数据列表'
                , cols: [[ //表头
                      { field: 'id', title: 'ID', sort: true }
                    , { field: 'key', title: '关键字', sort: true }
                    , { field: 'value', title: '值', sort: true }
                    , { field: 'createDateTime', title: '创建时间', sort: true }
                    , { field: 'isDeleted', title: '是否删除', sort: true }
                    , { field: 'deletedDateTime', title: '删除时间', sort: true }
                    , { fixed: 'right', title: '操作', toolbar: '#barDemo' }
                ]]
            });
            //头工具栏事件
            table.on('toolbar(myTable)', function (obj) {
                console.log(obj);
                var checkStatus = table.checkStatus(obj.config.id);
                switch (obj.event) {
                    case 'add':
                        location.href = '@Url.Content("~/KeyValue/Add")';
                        break;
                };
            });
            //监听行工具事件
            table.on('tool(myTable)', function (obj) {
                var data = obj.data;
                //console.log(obj)
                if (obj.event === 'del') {
                    layer.confirm('真的删除行么', function (index) {
                        fly.json('/Admin/Home/RequestArticles', { 'action': 'delete', 'data': JSON.stringify(data) }, function (res) {
                            layer.msg(res.msg);
                        });
                        obj.del();
                        layer.close(index);
                    });
                } else if (obj.event === 'edit') {
                    location.href = '@Url.Content("~/KeyValue/Edit/")' + data.id;
                }
            });

        });
    </script>

}